"""Reusable contracts and services for offline topic analysis."""

from src.analysis.cleaning import THANKS_TOKENS, classify, clean
from src.analysis.config import (
    AnalysisConfig,
    CleaningConfig,
    ClusteringConfig,
    DeduplicationConfig,
    EmbeddingConfig,
    load_analysis_config,
    save_analysis_config,
)
from src.analysis.dataset import SampleMetadata, create_research_sample, write_inspection_reports
from src.analysis.inspection import (
    DatasetFormat,
    DatasetInspection,
    FormatInspection,
    InspectionError,
    TextLengthStats,
    detect_dataset_format,
    inspect_comments_jsonl,
)
from src.analysis.models import (
    AnalysisCounts,
    AnalysisResult,
    CleaningDecision,
    CleaningReason,
    CleaningResult,
    CleaningStats,
    CommentRecord,
    DeduplicationResult,
    DeduplicationStats,
    DuplicateGroup,
    DuplicatePair,
    TopicAssignment,
    TopicSummary,
)
from src.analysis.schemas import (
    ANALYSIS_SCHEMA_VERSION,
    AnalysisRunMetadata,
    ClusterComment,
    ClusterRecord,
    ExportedComment,
)

__all__ = [
    "ANALYSIS_SCHEMA_VERSION",
    "THANKS_TOKENS",
    "AnalysisConfig",
    "AnalysisCounts",
    "AnalysisResult",
    "AnalysisRunMetadata",
    "CleaningConfig",
    "CleaningDecision",
    "CleaningReason",
    "CleaningResult",
    "CleaningStats",
    "ClusterComment",
    "ClusterRecord",
    "ClusteringConfig",
    "CommentRecord",
    "DatasetFormat",
    "DatasetInspection",
    "DeduplicationConfig",
    "DeduplicationResult",
    "DeduplicationStats",
    "DuplicateGroup",
    "DuplicatePair",
    "EmbeddingConfig",
    "ExportedComment",
    "FormatInspection",
    "InspectionError",
    "SampleMetadata",
    "TextLengthStats",
    "TopicAssignment",
    "TopicSummary",
    "classify",
    "clean",
    "create_research_sample",
    "detect_dataset_format",
    "inspect_comments_jsonl",
    "load_analysis_config",
    "save_analysis_config",
    "write_inspection_reports",
]
